routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \Illuminate\Support\Facades\Mail;

Route::get('/', function () {
    return view('admin.auth.login');
});


Route::group(['prefix' => 'dashboard', 'as' => 'admin.','middleware'=>'auth'], function () {
        Route::get('/','IndexController@index')->name('home');
        Route::resource('regions','RegionController');
});

Route::get('send-mail', function () {
    Mail::send(new \App\Mail\sendEmailMailable());
});

Route::get('/contact', 'HomeController@contact');
Route::post('/post-contact', 'HomeController@postContact');

require __DIR__ . '/auth.php';

app/Models/Region.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    use HasFactory;
    protected $guarded =[];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Scout\Searchable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, Searchable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function contact()
    {
        return view('contact');
    }

    public function postContact(Request $request){
//        $this->validate($request,[
//            'g-recaptcha-response' => 'required|captcha',
//
//        ]);
        dd($request->all());
    }
}

app/Http/Controllers/Admin/IndexController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function index()
    {
        return view('admin.layout.home');
    }
}

app/Http/Controllers/Admin/RegionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\RegionRequest;
use App\Models\Region;
use Illuminate\Http\Request;

class RegionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items=Region::all();
        return  view('admin.regions.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.regions.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RegionRequest $request)
    {
        $data=$request->all();
        Region::create($data);
        return redirect()->route("admin.regions.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Region $region)
    {
        return view('admin.regions.edit',['item'=>$region]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Region $region)
    {
        $region->update($request->all());
        return redirect()->route("admin.regions.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("admin.users.index",compact("items"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/admins/add.blade.php
@extends('admin.layout.app')

@section('title')
    إضافة  مدير
@stop
@section('content')

    <!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>إضافة مدير</h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{route('admin.admins.index')}}">
                            <button class="btn btn-danger1">كل المديرين</button>
                        </a>
                    </ul>
                </div>
                <div class="body">
                    {!!Form::open( ['route' => 'admin.admins.store' ,'class'=>'form phone_validate', 'method' => 'Post', 'enctype'=>"multipart/form-data",'id'=>"StoreForm",'files' => true]) !!}
                    @include('admin.admins.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layout.app')

@section('title')
    تعديل المدير
    {{ $item->name }}
@stop
@section('content')

    <!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>تعديل المدير {{ $item->name }}</h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{route('admin.admins.index')}}">
                            <button class="btn btn-danger1">كل المديرين</button>
                        </a>
                    </ul>
                </div>
                <div class="body">
                    {!!Form::model($item , ['route' => ['admin.admins.update' , $item->id] , 'method' => 'PATCH','enctype'=>"multipart/form-data",'files' => true]) !!}
                        @include('admin.admins.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>


    <!-- #END# Basic Validation -->
@endsection

resources/views/admin/admins/form.blade.php
@include('admin.common.alert')
@include('admin.common.errors')

<div class="form-group form-float">
    <label class="form-label">الإسم</label>
    <div class="form-line">
        {!! Form::text("name",null,['class'=>'form-control','placeholder'=>'  الاسم  '])!!}
    </div>
</div>

<div class="form-group form-float">
    <label class="form-label">الإيميل</label>
    {!! Form::email("email",null,['class'=>'form-control','placeholder'=>'  الايميل '])!!}
    <div class="form-line">
    </div>
</div>

<div class="form-group form-float">
    <label class="form-label">رقم الهاتف</label>
    {!! Form::number("phone",null,['class'=>'form-control','placeholder'=>'رقم الهاتف'])!!}
    <div class="form-line">
    </div>
</div>


<div class="form-group form-float">
    <label class="form-label">كلمة المرور</label>
    {!! Form::input('password','password',null,['class'=>'form-control','placeholder'=>'كلمة المرور']) !!}
    <div class="form-line">
    </div>
</div>

<div class="form-group form-float">
    <label class="form-label">تكرار كلمة المرور</label>
    {!! Form::input('password','password_confirmation',null,['class'=>'form-control','placeholder'=>'تكرار كلمة المرور']) !!}

    <div class="form-line">
    </div>
</div>
@if (isset($item->image))
    <div class="form-group form-float">
        <label class="form-label">الصورة الحالية للأدمن :</label>
        <div class="form-line">
            <img class="img-preview" src="{{$item->image}}" style="width: 50px; height: 50px">
        </div>
    </div>
@endif

<div class="form-group form-float">
    <label class="form-label">صورة للأدمن </label>
    <div class="form-line">
        {!! Form::file("image",null,['class'=>'form-control'])!!}
    </div>
</div>


<div class="form-group">
    {!! Form::radio("is_active",1,null,['class'=>'with-gap','id'=>'radio_3']) !!}
    <label for="radio_3"> تفعيل </label>

    {!! Form::radio("is_active",0,null,['class'=>'with-gap','id'=>'radio_4']) !!}
    <label for="radio_4">عدم تفعيل</label>
</div>

{!! Form::input('hidden','role','admin',['class'=>'form-control']) !!}

@if(isset($item->id))
    {!! Form::input('hidden','id',$item->id,['class'=>'form-control']) !!}
@endif
<button class="btn btn-primary waves-effect btn-submit" type="submit">حفظ</button>

resources/views/admin/admins/index.blade.php
@extends('admin.layout.app')

@section('title')
    أعضاء إدارة النظام
@endsection
@section('header')
    @include('admin.datatable.headers')
@endsection
@section('content')
    @include('admin.common.alert')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        أعضاء إدارة النظام
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{route('admin.admins.create')}}">
                            <button class="btn btn-success">إضافة عضو جديد</button>
                        </a>
                    </ul>
                </div>
                <div class="body">
                    <table class="table js-basic-example display responsive nowrap table-bordered table-striped table-hover dataTable responsive js-exportable  data-table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>الإسم</th>
                            <th>الايميل</th>
                            <th>الهاتف</th>
                            <th>حالة الحساب</th>
                            <th>صورة العضو</th>
                            <th>تغيير حالة الحساب</th>
                            <th>العمليات</th>
                        </tr>
                        </thead>
                        <tbody>
                  @foreach($items as $key=>$item)
                      <tr>
                          <td>{{++$key}}</td>
                          <td>{{$item->name}}</td>
                          <td>{{$item->email}}</td>
                          <td>{{$item->phone}}</td>
                          <td>{{AccountStatus($item->is_active)}}</td>
                          <td>
                            <img src="{{$item->image}}" style="width: 50px; height: 50px">
                          </td>
                          <td>

                              @if($item->is_active == 1)
                                  <a href="{{route('admin.Deactivate',$item->id)}}"
                                     class="btn btn-xs btn-danger"><i class="fa fa-times"></i> </a>
                              @else
                                  <a href="{{route('admin.Activate',$item->id)}}"
                                     class="btn btn-xs btn-success"><i class="fa fa-check"></i> </a>
                              @endif
                          </td>
                          <td>
                              <a href="{{route('admin.admins.edit',$item->id)}}"
                                 class="btn btn-info btn-circle"><i style="padding-top:5px;padding-left: 6px;"
                                                                    class="fa fa-pencil"></i></a>
                              @if($item->email== auth()->user()->email)
                              @else
                                  <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip"
                                     data-original-title="حذف" class="btn btn-danger btn-circle"><i
                                              style="padding-top: 5px;padding-left: 4px;"
                                              class="fa fa-trash-o"></i></a>
                              @endif
                              {!!Form::open( ['route' => ['admin.admins.destroy',$item->id] ,'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                              {!!Form::close() !!}


                          </td>

                      </tr>
                  @endforeach

                  </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->

@endsection


@section('footer')
    @include('admin.datatable.scripts')
    <script>
        function Delete(id) {
            var item_id = id;
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذا الأدمن ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function (isConfirm) {
                if (isConfirm) {
                    document.getElementById('delete-form' + item_id).submit();
                } else {
                    swal("تم االإلفاء", "حذف  الأدمن تم الغاؤه", 'info', {buttons: 'موافق'});
                }
            });
        }
    </script>
@endsection

resources/views/admin/common/alert.blade.php
@if (session('alert'))
    <div class="alert alert-success">
        {{ session('alert') }}
    </div>
@endif


@if (session('fail'))
    <div class="alert alert-danger">
        {{ session('fail') }}
    </div>
@endif

resources/views/admin/common/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
    <ul class="list-unstyled mx-0 px-0" dir="rtl">
        @foreach ($errors->all() as $error)
            <li class="text-danger">{{$error}}</li>
        @endforeach
    </ul>
    </div>
@endif

resources/views/admin/datatable/cart_scripts.blade.php
<!-- Jquery DataTable Plugin Js -->
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js
"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js
"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js
"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js
"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js
"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js
"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js
"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
<script>
    $(document).ready(function() {
        var table = $('.table').DataTable( {
            // order: [[ 0, "desc" ]],
            responsive: true,
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'print'
            ]
        } );
    } );
</script>

resources/views/admin/datatable/headers.blade.php
<!--
{{Html::style('admin/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}
{{Html::style('https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css')}}
{{Html::style('admin/css/index_style.css')}}
-->
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css
" rel="stylesheet">
<link href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.dataTables.min.css
" rel="stylesheet">

resources/views/admin/datatable/scripts.blade.php
<!-- Jquery DataTable Plugin Js -->
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js
"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js
"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js
"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js
"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js
"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js
"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js
"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
<script>
$(document).ready(function() {
    var table = $('.table').DataTable( {
        order: [[ 0, "desc" ]],
        responsive: true,
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel',{ extend: 'print',
                customize: function (win) {
                    $(win.document.body).css('direction', 'rtl');
                }}
        ]
    } );
} );
</script>

resources/views/admin/layout/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    <title>لوحة التحكم - @yield('title')</title>
    @yield('header')
    @include('admin.layout.styles')
    @yield('custom_styles')
</head>

<body class="theme-red">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>

                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
            <i class="fas fa-futbol"></i>
        </div>
        <p>رجاءً انتظر...</p>
    </div>
</div>
<!-- #END# Page Loader -->

<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->

<!-- Top Bar -->
<nav class="navbar">
    <div class="logo-dashboard text-center">

    </div>

</nav>
<!-- #Top Bar -->
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="image">
                <img src="{{url('admin/images/user.png')}}" width="48" height="48" alt="User"/>
                {{--                 <h8 style="color: red">{{auth()->user()->name}}</h8>--}}
            </div>
            <div class="info-container">
                <div class="name ar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></div>
                <div class="email ar"></div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-left">
                        <form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                        <li><a class="ar" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();" href="{{url('/logout')}}"><i
                                    class="material-icons">input</i>تسجيل الخروج</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">القائمة الرئيسية</li>
                @include('admin.layout.nav')
            </ul>
        </div>
        <!-- #Menu -->
    </aside>
    <!-- #END# Left Sidebar -->
</section>

<section class="content">
    <div class="container-fluid">
        @yield('content')
        @include('sweet::alert')
    </div>
</section>


@include('admin.layout.scripts')

@yield('footer')
@stack('scripts')

</body>
</html>

resources/views/admin/layout/home.blade.php
@extends('admin.layout.app')

@section('title')
    الصفحه الرئيسه
@stop

@section('content')
    <!-- Widgets -->
    <div class="row clearfix">

    </div>

@stop

resources/views/admin/layout/nav.blade.php
<li>
    <a class="check_active" href="{{route('admin.home')}}">
        <i class="material-icons">home</i>
        <span>الصفحه الرئيسه والاحصائيات</span>
    </a>

</li>

<li class="header">عام</li>

<li>
    <a href="javascript:void(0);" class="menu-toggle">
        <i class="material-icons">add_to_photos</i>

        <span>المدن</span>
    </a>
    <ul class="ml-menu">
        <li>
            <a class="check_active" href="{{route('admin.regions.index')}}">

                <span>عرض المدن </span>
            </a>
        </li>

        <li>
            <a class="check_active" href="{{route('admin.regions.create')}}">

                <span>اضافه جديد</span>
            </a>
        </li>
    </ul>
</li>

resources/views/admin/regions/add.blade.php
@extends('admin.layout.app')

@section('title')
    اضافة مدينة جديدة
@stop
@section('content')

    <!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>اضافة مدينة جديدة</h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{route('admin.regions.index')}}">
                            <button class="btn btn-danger1">كل المدن</button>
                        </a>
                    </ul>
                </div>
                <div class="body">
                    {!!Form::open( ['route' => 'admin.regions.store' ,'class'=>'form phone_validate', 'enctype'=>"multipart/form-data",'files' => true]) !!}
                    @include('admin.regions.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Validation -->
@endsection

@push('scripts')
    <script src="{{ asset('admin/map.js') }}"></script>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCsT140mx0UuES7ZwcfY28HuTUrTnDhxww&callback=initMap&libraries=&v=weekly"></script>
@endpush

resources/views/admin/regions/index.blade.php
@extends('admin.layout.app')

@section('title')
المدن
@stop
@section('header')
    @include('admin.datatable.headers')
@stop
@section('content')
    @include('admin.common.alert')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        المدن
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{route('admin.regions.create')}}">
                            <button class="btn btn-success"> اضافة مدينة جديدة</button>
                        </a>
                    </ul>

                </div>
                <div class="body">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable data-table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>الإسم باللغة العربية</th>
                            <th>العمليات</th>
                        </tr>
                        </thead>
                        <tbody>
                  @foreach($items as $key=>$item)
                      <tr>
                          <td>{{++$key}}</td>
                          <td>{{$item->name}}</td>
                          <td>
                              <a href="{{route('admin.regions.edit',$item->id)}}"
                                 class="btn btn-info btn-circle"><i style="padding-top:5px;padding-left: 6px;"
                                                                    class="fa fa-pencil"></i></a>

                                  <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip"
                                     data-original-title="حذف" class="btn btn-danger btn-circle"><i
                                              style="padding-top: 5px;padding-left: 4px;"
                                              class="fa fa-trash-o"></i></a>
                              {!!Form::open( ['route' => ['admin.regions.destroy',$item->id] ,'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                              {!!Form::close() !!}


                          </td>

                      </tr>
                  @endforeach

                  </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->

@endsection


@section('footer')
    @include('admin.datatable.scripts')
    <script>
        function Delete(id) {
            var item_id = id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذه المدينة؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function (isConfirm) {
                if (isConfirm) {
                    document.getElementById('delete-form' + item_id).submit();
                } else {
                    swal("تم االإلفاء", "حذف  القسم تم الغاؤه", 'info', {buttons: 'موافق'});
                }
            });
        }
    </script>
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>